/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lvc.cds;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
    
    }
}
